import { KnowledgeCategory, SkillScore, CaseStudy, Exam, Book } from './types'

const now = new Date().toISOString()

// Helper
let _id = 1
const id = (prefix: string) => `${prefix}-${_id++}`

// ─── MBA Knowledge Map — 14 Categories ───────────────────────────────────────

export const SEED_KNOWLEDGE: KnowledgeCategory[] = [
  {
    id: 'cat-finance',
    name: 'Finance',
    icon: '💰',
    description: 'Master financial statements, unit economics, and capital allocation to run a profitable coffee business.',
    completionPercentage: 0,
    updatedAt: now,
    topics: [
      {
        id: 'fin-1', name: 'Financial Statements',
        subtopics: ['Income Statement (P&L)', 'Balance Sheet', 'Cash Flow Statement', 'Statement of Equity'],
        learningObjectives: ['Read and interpret a P&L', 'Understand assets vs liabilities', 'Track cash vs profit difference'],
        requiredSkills: ['Basic arithmetic', 'Spreadsheet basics'],
        difficulty: 'beginner', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'fin-2', name: 'Unit Economics',
        subtopics: ['Cost per Cup', 'Contribution Margin', 'Customer Lifetime Value (LTV)', 'Customer Acquisition Cost (CAC)', 'LTV:CAC Ratio', 'Payback Period'],
        learningObjectives: ['Calculate exact cost per beverage', 'Model LTV for a loyalty customer', 'Determine viable CAC ceiling'],
        requiredSkills: ['P&L understanding'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 5,
      },
      {
        id: 'fin-3', name: 'Budgeting & Forecasting',
        subtopics: ['Annual Budget', 'Rolling Forecast', 'Scenario Planning', 'Variance Analysis', 'Zero-Based Budgeting'],
        learningObjectives: ['Build a 12-month branch budget', 'Create 3-scenario financial model', 'Explain variance to plan'],
        requiredSkills: ['Financial Statements', 'Excel/Sheets'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 6,
      },
      {
        id: 'fin-4', name: 'Break-even Analysis',
        subtopics: ['Fixed vs Variable Costs', 'Break-even Point', 'Margin of Safety', 'Operating Leverage', 'Break-even per SKU'],
        learningObjectives: ['Calculate branch break-even in cups/day', 'Identify highest-margin products', 'Model impact of rent changes'],
        requiredSkills: ['Unit Economics'],
        difficulty: 'beginner', completed: false, notes: '', estimatedHours: 3,
      },
      {
        id: 'fin-5', name: 'Return on Investment (ROI)',
        subtopics: ['ROI Formula', 'Payback Period', 'Net Present Value (NPV)', 'Internal Rate of Return (IRR)', 'Return on Equity'],
        learningObjectives: ['Calculate ROI for new equipment', 'Apply NPV to branch expansion decision', 'Compare investment alternatives'],
        requiredSkills: ['Financial Statements', 'Break-even Analysis'],
        difficulty: 'advanced', completed: false, notes: '', estimatedHours: 5,
      },
      {
        id: 'fin-6', name: 'Cash Flow Management',
        subtopics: ['Cash Flow Cycle', 'Working Capital', 'Days Sales Outstanding', 'Cash Conversion Cycle', 'Cash Flow Forecasting'],
        learningObjectives: ['Build a 13-week cash flow forecast', 'Identify cash flow risk periods', 'Optimize working capital'],
        requiredSkills: ['Financial Statements'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'fin-7', name: 'Valuation Basics',
        subtopics: ['Revenue Multiples', 'EBITDA Multiples', 'DCF Basics', 'Comparable Transactions', 'Coffee Shop Valuation Norms'],
        learningObjectives: ['Estimate CoffeePlace valuation range', 'Understand what drives cafe valuations', 'Prepare for investor conversations'],
        requiredSkills: ['ROI', 'Unit Economics'],
        difficulty: 'advanced', completed: false, notes: '', estimatedHours: 5,
      },
    ],
  },
  {
    id: 'cat-accounting',
    name: 'Accounting',
    icon: '📊',
    description: 'Accounting fundamentals every founder needs to stay compliant, make decisions, and avoid surprises.',
    completionPercentage: 0,
    updatedAt: now,
    topics: [
      {
        id: 'acc-1', name: 'Accounting Fundamentals',
        subtopics: ['Debits & Credits', 'Chart of Accounts', 'Double-Entry Bookkeeping', 'Accounting Equation'],
        learningObjectives: ['Understand the accounting equation', 'Set up a chart of accounts for a cafe', 'Record basic transactions'],
        requiredSkills: [],
        difficulty: 'beginner', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'acc-2', name: 'Revenue Recognition',
        subtopics: ['Accrual vs Cash Accounting', 'Revenue Recognition Principles', 'Deferred Revenue', 'Gift Cards & Loyalty Points'],
        learningObjectives: ['Choose right accounting method', 'Handle loyalty point accounting', 'Recognize gift card liability'],
        requiredSkills: ['Accounting Fundamentals'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 3,
      },
      {
        id: 'acc-3', name: 'Cost Accounting',
        subtopics: ['COGS Calculation', 'Food & Beverage Cost %', 'Labor Cost %', 'Overhead Allocation', 'Standard Costing'],
        learningObjectives: ['Calculate exact food cost %', 'Benchmark labor cost against industry', 'Price products for target margin'],
        requiredSkills: ['Accounting Fundamentals'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 5,
      },
      {
        id: 'acc-4', name: 'Payroll & HR Accounting',
        subtopics: ['Payroll Processing', 'Social Insurance', 'Allowances', 'End-of-Service Benefits', 'Monthly Payroll Journal'],
        learningObjectives: ['Process monthly payroll accurately', 'Calculate end-of-service provisions', 'Record payroll journal entries'],
        requiredSkills: ['Accounting Fundamentals'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'acc-5', name: 'Tax Fundamentals',
        subtopics: ['VAT/Sales Tax', 'Corporate Tax', 'Withholding Tax', 'Tax Planning Basics', 'Filing Deadlines'],
        learningObjectives: ['Understand local tax obligations', 'Plan for tax payments', 'Work effectively with accountants'],
        requiredSkills: ['Revenue Recognition'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 3,
      },
    ],
  },
  {
    id: 'cat-marketing',
    name: 'Marketing',
    icon: '📣',
    description: 'Drive awareness, attract the right customers, and build a marketing engine that scales.',
    completionPercentage: 0,
    updatedAt: now,
    topics: [
      {
        id: 'mkt-1', name: 'Market Research',
        subtopics: ['Customer Segmentation', 'Ideal Customer Profile (ICP)', 'Competitor Analysis', 'Market Sizing (TAM/SAM/SOM)', 'Surveys & Interviews'],
        learningObjectives: ['Define CoffeePlace ICP', 'Estimate local market size', 'Run 10 customer interviews'],
        requiredSkills: [],
        difficulty: 'beginner', completed: false, notes: '', estimatedHours: 5,
      },
      {
        id: 'mkt-2', name: 'Digital Marketing',
        subtopics: ['Instagram Marketing', 'TikTok Strategy', 'Google My Business', 'Paid Social (Meta Ads)', 'Google Ads Basics'],
        learningObjectives: ['Launch a Google My Business profile', 'Run a Meta Ads campaign', 'Build an organic Instagram strategy'],
        requiredSkills: ['Market Research'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 8,
      },
      {
        id: 'mkt-3', name: 'Content Marketing',
        subtopics: ['Content Calendar', 'Coffee Education Content', 'Behind the Scenes', 'User-Generated Content', 'Storytelling Framework'],
        learningObjectives: ['Build 30-day content calendar', 'Create 5 pillar content pieces', 'Launch UGC campaign'],
        requiredSkills: ['Digital Marketing'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 6,
      },
      {
        id: 'mkt-4', name: 'Email & SMS Marketing',
        subtopics: ['List Building', 'Welcome Sequences', 'Campaign Structure', 'Segmentation', 'A/B Testing Subject Lines'],
        learningObjectives: ['Build email list to 500 subscribers', 'Launch automated welcome sequence', 'Achieve 35%+ open rate'],
        requiredSkills: ['Digital Marketing'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'mkt-5', name: 'Customer Retention Marketing',
        subtopics: ['Loyalty Programs', 'Referral Programs', 'Win-Back Campaigns', 'VIP Tiers', 'NPS-Based Campaigns'],
        learningObjectives: ['Design loyalty program', 'Launch referral program', 'Reduce churn with win-back flow'],
        requiredSkills: ['Email Marketing', 'Customer Research'],
        difficulty: 'advanced', completed: false, notes: '', estimatedHours: 5,
      },
    ],
  },
  {
    id: 'cat-branding',
    name: 'Branding',
    icon: '✨',
    description: 'Build a brand people remember, love, and advocate for — your most durable competitive advantage.',
    completionPercentage: 0,
    updatedAt: now,
    topics: [
      {
        id: 'brnd-1', name: 'Brand Strategy',
        subtopics: ['Brand Purpose & Why', 'Brand Positioning Statement', 'Value Proposition', 'Target Audience Definition', 'Brand Archetypes'],
        learningObjectives: ['Write CoffeePlace brand manifesto', 'Complete brand positioning canvas', 'Identify brand archetype'],
        requiredSkills: [],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 5,
      },
      {
        id: 'brnd-2', name: 'Visual Identity',
        subtopics: ['Logo & Mark', 'Color Palette', 'Typography', 'Brand Guidelines', 'Packaging Design', 'In-store Visual Experience'],
        learningObjectives: ['Create CoffeePlace brand guidelines', 'Audit visual consistency across touchpoints', 'Brief a designer effectively'],
        requiredSkills: ['Brand Strategy'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'brnd-3', name: 'Brand Voice & Messaging',
        subtopics: ['Tone of Voice', 'Messaging Hierarchy', 'Tagline Development', 'Menu Language', 'Social Media Voice'],
        learningObjectives: ['Write brand voice guide', 'Create 3 brand messaging pillars', 'Audit all customer touchpoints for consistency'],
        requiredSkills: ['Brand Strategy'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 3,
      },
      {
        id: 'brnd-4', name: 'Brand Experience Design',
        subtopics: ['In-Store Atmosphere', 'Sensory Branding (Smell, Sound, Sight)', 'Packaging as Brand Touch', 'Staff as Brand Ambassadors', 'Branded Rituals'],
        learningObjectives: ['Audit CoffeePlace brand experience', 'Design 3 branded rituals', 'Create ambiance guidelines'],
        requiredSkills: ['Visual Identity', 'Brand Voice'],
        difficulty: 'advanced', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'brnd-5', name: 'Community Building',
        subtopics: ['Brand Community Strategy', 'Events & Activations', 'Micro-influencer Partnerships', 'Local Collaborations', 'Ambassador Programs'],
        learningObjectives: ['Host first brand community event', 'Partner with 3 local businesses', 'Launch ambassador program'],
        requiredSkills: ['Brand Experience'],
        difficulty: 'advanced', completed: false, notes: '', estimatedHours: 5,
      },
    ],
  },
  {
    id: 'cat-operations',
    name: 'Operations',
    icon: '⚙️',
    description: 'Build repeatable, scalable systems that deliver consistent quality without depending on you.',
    completionPercentage: 0,
    updatedAt: now,
    topics: [
      {
        id: 'ops-1', name: 'SOP Development',
        subtopics: ['Process Mapping', 'SOP Writing Framework', 'Visual SOPs', 'Training Integration', 'SOP Versioning'],
        learningObjectives: ['Map top 10 cafe processes', 'Write 5 core SOPs', 'Create visual SOP cards for bar'],
        requiredSkills: [],
        difficulty: 'beginner', completed: false, notes: '', estimatedHours: 6,
      },
      {
        id: 'ops-2', name: 'Quality Control Systems',
        subtopics: ['Barista Quality Standards', 'Espresso Calibration', 'Sensory Evaluation', 'Quality Audit Checklists', 'Mystery Shopper Program'],
        learningObjectives: ['Build quality scorecard', 'Run monthly quality audits', 'Implement espresso calibration SOP'],
        requiredSkills: ['SOP Development'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 5,
      },
      {
        id: 'ops-3', name: 'Inventory Management',
        subtopics: ['Par Levels', 'FIFO', 'Waste Tracking', 'Reorder Points', 'Inventory Turns', 'Supplier Lead Times'],
        learningObjectives: ['Set par levels for all items', 'Build weekly inventory count system', 'Calculate inventory turn rate'],
        requiredSkills: ['SOP Development'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'ops-4', name: 'Supply Chain Management',
        subtopics: ['Supplier Selection', 'Green Coffee Sourcing', 'Roaster Relationships', 'Supplier Scorecards', 'Backup Suppliers'],
        learningObjectives: ['Build supplier scorecard', 'Negotiate supply agreements', 'Identify backup suppliers for all key items'],
        requiredSkills: ['Inventory Management'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'ops-5', name: 'Technology & POS Systems',
        subtopics: ['POS Selection', 'Ordering & Delivery Tech', 'Loyalty Tech Integration', 'Data from POS', 'Staff Scheduling Software'],
        learningObjectives: ['Evaluate and select POS system', 'Integrate loyalty with POS', 'Extract sales data for decision-making'],
        requiredSkills: [],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'ops-6', name: 'Multi-Branch Operations',
        subtopics: ['Central Operations Model', 'Branch Manager Role', 'Standardization vs Localization', 'Operations Dashboard', 'Brand Consistency Audits'],
        learningObjectives: ['Design multi-branch ops model', 'Build branch manager KPI scorecard', 'Create brand audit checklist'],
        requiredSkills: ['SOP Development', 'Quality Control'],
        difficulty: 'advanced', completed: false, notes: '', estimatedHours: 6,
      },
    ],
  },
  {
    id: 'cat-leadership',
    name: 'Leadership',
    icon: '🎯',
    description: 'Develop the leadership capability to inspire, align, and grow a world-class team.',
    completionPercentage: 0,
    updatedAt: now,
    topics: [
      {
        id: 'lead-1', name: 'Leadership Foundations',
        subtopics: ['Leadership vs Management', 'Situational Leadership', 'Leadership Styles', 'Self-Awareness as Leader', 'Founder Leadership Traps'],
        learningObjectives: ['Identify your default leadership style', 'List your top 5 leadership principles', 'Write personal leadership manifesto'],
        requiredSkills: [],
        difficulty: 'beginner', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'lead-2', name: 'Communication & Influence',
        subtopics: ['Active Listening', 'Feedback Frameworks (SBI)', 'Difficult Conversations', 'Public Speaking', 'Written Communication'],
        learningObjectives: ['Practice SBI feedback in 3 real situations', 'Lead a difficult conversation', 'Deliver team meeting presentations'],
        requiredSkills: ['Leadership Foundations'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 5,
      },
      {
        id: 'lead-3', name: 'Delegation & Empowerment',
        subtopics: ['Delegation Framework', 'Task vs Result Delegation', 'Accountability Without Micromanagement', 'Decision Rights', 'Trust Building'],
        learningObjectives: ['Delegate 3 tasks you currently own', 'Create decision rights matrix', 'Build accountability system without micromanaging'],
        requiredSkills: ['Communication'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'lead-4', name: 'Vision & Culture',
        subtopics: ['Setting Company Vision', 'Translating Vision to Daily Behavior', 'Cultural Rituals', 'Values in Hiring & Firing', 'Psychological Safety'],
        learningObjectives: ['Write 5-year company vision', 'Define 5 non-negotiable culture values', 'Build 3 cultural rituals for your team'],
        requiredSkills: ['Leadership Foundations'],
        difficulty: 'advanced', completed: false, notes: '', estimatedHours: 5,
      },
    ],
  },
  {
    id: 'cat-hr',
    name: 'HR',
    icon: '👥',
    description: 'Build systems that attract great people, develop them fast, and retain them long-term.',
    completionPercentage: 0,
    updatedAt: now,
    topics: [
      {
        id: 'hr-1', name: 'Hiring Systems',
        subtopics: ['Job Profile Design', 'Sourcing Channels', 'Interview Scorecard', 'Skills Assessment (Barista Test)', 'Culture-Fit Evaluation', 'Offer Design'],
        learningObjectives: ['Write job profiles for all roles', 'Build interview scorecard', 'Design barista skills test'],
        requiredSkills: [],
        difficulty: 'beginner', completed: false, notes: '', estimatedHours: 5,
      },
      {
        id: 'hr-2', name: 'Onboarding',
        subtopics: ['30-60-90 Day Plan', 'First Week Checklist', 'Buddy System', 'Skills Certification', 'Culture Immersion'],
        learningObjectives: ['Build 30-day barista onboarding program', 'Create first-day checklist', 'Design skills certification path'],
        requiredSkills: ['Hiring Systems'],
        difficulty: 'beginner', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'hr-3', name: 'Performance Management',
        subtopics: ['KPIs per Role', '1-on-1 Structure', 'Quarterly Reviews', 'Performance Improvement Plans', 'Recognition Programs'],
        learningObjectives: ['Define KPIs for barista role', 'Build monthly 1-on-1 agenda', 'Run quarterly review cycle'],
        requiredSkills: ['Onboarding'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'hr-4', name: 'Compensation & Benefits',
        subtopics: ['Salary Benchmarking', 'Variable Pay Design', 'Non-Monetary Benefits', 'Tip Policy', 'Career Progression Bands'],
        learningObjectives: ['Benchmark salaries in your market', 'Design incentive structure', 'Create career progression ladder'],
        requiredSkills: [],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 4,
      },
    ],
  },
  {
    id: 'cat-entrepreneurship',
    name: 'Entrepreneurship',
    icon: '🚀',
    description: 'The founder mindset, business model design, and fundraising skills to build and scale.',
    completionPercentage: 0,
    updatedAt: now,
    topics: [
      {
        id: 'ent-1', name: 'Business Model Design',
        subtopics: ['Business Model Canvas', 'Value Proposition Canvas', 'Revenue Streams', 'Cost Structure', 'Key Partners & Activities'],
        learningObjectives: ['Complete Business Model Canvas for CoffeePlace', 'Identify 3 alternative revenue streams', 'Map key partnerships'],
        requiredSkills: [],
        difficulty: 'beginner', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'ent-2', name: 'Founder Mindset',
        subtopics: ['Growth Mindset', 'Risk Tolerance & Management', 'Resilience Building', 'Decision-Making Under Uncertainty', 'Avoiding Founder Traps'],
        learningObjectives: ['Identify your 3 biggest founder blind spots', 'Build decision-making framework', 'Create personal resilience rituals'],
        requiredSkills: [],
        difficulty: 'beginner', completed: false, notes: '', estimatedHours: 3,
      },
      {
        id: 'ent-3', name: 'Fundraising & Capital',
        subtopics: ['Bootstrapping Strategy', 'Bank Financing', 'Angel Investors', 'Pitch Deck Structure', 'Cap Table Basics', 'Dilution & Valuation'],
        learningObjectives: ['Build investor pitch deck', 'Model funding scenarios', 'Understand cap table implications'],
        requiredSkills: ['Business Model', 'Valuation Basics'],
        difficulty: 'advanced', completed: false, notes: '', estimatedHours: 8,
      },
      {
        id: 'ent-4', name: 'Legal Fundamentals',
        subtopics: ['Business Structure (LLC, Corp)', 'Commercial Lease Basics', 'IP Protection', 'Employment Law', 'Partnership Agreements'],
        learningObjectives: ['Understand optimal legal structure', 'Negotiate lease terms', 'Protect brand IP'],
        requiredSkills: [],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 4,
      },
    ],
  },
  {
    id: 'cat-strategy',
    name: 'Strategy',
    icon: '♟️',
    description: "Think like a strategist. Build a durable competitive advantage that can't be easily copied.",
    completionPercentage: 0,
    updatedAt: now,
    topics: [
      {
        id: 'strat-1', name: "Porter's Five Forces",
        subtopics: ['Competitive Rivalry', 'Buyer Power', 'Supplier Power', 'Threat of New Entrants', 'Threat of Substitutes', 'Application to F&B'],
        learningObjectives: ['Apply Five Forces to local coffee market', 'Identify your strongest competitive moat', 'Design strategies against each force'],
        requiredSkills: [],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'strat-2', name: 'Blue Ocean Strategy',
        subtopics: ['ERRC Framework (Eliminate, Reduce, Raise, Create)', 'Strategy Canvas', 'Value Innovation', 'Non-Customer Analysis'],
        learningObjectives: ['Build CoffeePlace strategy canvas vs competitors', 'Apply ERRC to identify blue ocean', 'Find 3 un-served customer segments'],
        requiredSkills: ["Porter's Five Forces"],
        difficulty: 'advanced', completed: false, notes: '', estimatedHours: 5,
      },
      {
        id: 'strat-3', name: 'Strategic Planning & OKRs',
        subtopics: ['Vision, Mission, Values', 'Annual Strategic Priorities', 'OKR Framework', 'Strategy Execution', 'Strategic Review Cadence'],
        learningObjectives: ['Write 3-year strategic plan', 'Set quarterly OKRs', 'Build monthly strategy review process'],
        requiredSkills: [],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 5,
      },
      {
        id: 'strat-4', name: 'Competitive Intelligence',
        subtopics: ['Competitor Mapping', 'Mystery Shopping', 'Pricing Intelligence', 'Benchmarking', 'SWOT Analysis'],
        learningObjectives: ['Profile top 5 competitors across 20 dimensions', 'Run quarterly competitive intelligence process', 'Build competitor monitoring system'],
        requiredSkills: [],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 4,
      },
    ],
  },
  {
    id: 'cat-analytics',
    name: 'Analytics',
    icon: '📈',
    description: 'Use data to make better decisions, find hidden opportunities, and measure what actually matters.',
    completionPercentage: 0,
    updatedAt: now,
    topics: [
      {
        id: 'anl-1', name: 'Cafe KPI Framework',
        subtopics: ['Revenue per Seat', 'Average Ticket', 'Customer Count', 'Table Turnover', 'Same-Store Sales Growth', 'Sales per Labor Hour'],
        learningObjectives: ['Define 12 core KPIs for CoffeePlace', 'Build KPI tracking dashboard', 'Set targets for each KPI'],
        requiredSkills: [],
        difficulty: 'beginner', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'anl-2', name: 'Customer Analytics',
        subtopics: ['Purchase Frequency', 'Average Order Value', 'Cohort Analysis', 'RFM Analysis (Recency, Frequency, Monetary)', 'Churn Rate'],
        learningObjectives: ['Segment customers by RFM', 'Calculate monthly churn rate', 'Identify your top 20% customers'],
        requiredSkills: ['Cafe KPI Framework'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 5,
      },
      {
        id: 'anl-3', name: 'Financial Analytics',
        subtopics: ['Gross Margin Analysis', 'Product Mix Analysis', 'Time-of-Day Analysis', 'Staff Productivity Analytics', 'Waste Analytics'],
        learningObjectives: ['Identify top/bottom margin products', 'Find peak/off-peak opportunity windows', 'Calculate labor productivity score'],
        requiredSkills: ['Cafe KPI Framework'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 5,
      },
      {
        id: 'anl-4', name: 'Data-Driven Decision Making',
        subtopics: ['Hypothesis Testing', 'A/B Testing for Cafes', 'Decision Trees', 'Data Storytelling', 'Dashboard Design'],
        learningObjectives: ['Run your first A/B test (e.g. menu item)', 'Build executive dashboard', 'Present data-backed recommendation to team'],
        requiredSkills: ['Customer Analytics', 'Financial Analytics'],
        difficulty: 'advanced', completed: false, notes: '', estimatedHours: 5,
      },
    ],
  },
  {
    id: 'cat-negotiation',
    name: 'Negotiation',
    icon: '🤝',
    description: 'Every deal you negotiate — rent, suppliers, staff, partnerships — directly impacts profitability.',
    completionPercentage: 0,
    updatedAt: now,
    topics: [
      {
        id: 'neg-1', name: 'Negotiation Fundamentals',
        subtopics: ['BATNA (Best Alternative)', 'ZOPA (Zone of Possible Agreement)', 'Principled Negotiation (Fisher & Ury)', 'Anchoring', 'Framing'],
        learningObjectives: ['Understand BATNA and ZOPA', 'Apply principled negotiation in real scenario', 'Practice anchoring technique'],
        requiredSkills: [],
        difficulty: 'beginner', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'neg-2', name: 'Supplier Negotiations',
        subtopics: ['Coffee Bean Pricing', 'Minimum Order Quantities', 'Payment Terms', 'Exclusivity Clauses', 'Price Escalation Clauses'],
        learningObjectives: ['Negotiate 60-day payment terms', 'Secure volume discount structure', 'Build supplier contract template'],
        requiredSkills: ['Negotiation Fundamentals'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'neg-3', name: 'Commercial Lease Negotiation',
        subtopics: ['Rent-Free Period', 'Fit-Out Contribution', 'Break Clauses', 'Rent Reviews', 'Exclusivity Clauses', 'CAM Charges'],
        learningObjectives: ['Negotiate rent-free fit-out period', 'Secure favorable break clause', 'Understand all lease costs (CAM, insurance)'],
        requiredSkills: ['Negotiation Fundamentals'],
        difficulty: 'advanced', completed: false, notes: '', estimatedHours: 5,
      },
      {
        id: 'neg-4', name: 'Partnership & Investment Negotiations',
        subtopics: ['Equity vs Debt Terms', 'Investor Term Sheets', 'Partnership Agreement Key Clauses', 'Exit Provisions', 'Board Seat Negotiations'],
        learningObjectives: ['Read and mark up a term sheet', 'Negotiate founder-friendly terms', 'Structure a fair partnership agreement'],
        requiredSkills: ['Negotiation Fundamentals', 'Legal Fundamentals'],
        difficulty: 'advanced', completed: false, notes: '', estimatedHours: 5,
      },
    ],
  },
  {
    id: 'cat-sales',
    name: 'Sales',
    icon: '💼',
    description: 'Build a systematic approach to growing revenue — from daily upselling to corporate accounts.',
    completionPercentage: 0,
    updatedAt: now,
    topics: [
      {
        id: 'sales-1', name: 'In-Store Sales Optimization',
        subtopics: ['Menu Psychology', 'Upselling Techniques', 'Add-On Sales Training', 'Counter Merchandising', 'Suggestive Selling Scripts'],
        learningObjectives: ['Train team on upselling', 'Redesign menu for higher average ticket', 'Measure upsell conversion rate'],
        requiredSkills: [],
        difficulty: 'beginner', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'sales-2', name: 'Corporate & B2B Sales',
        subtopics: ['Office Coffee Programs', 'Corporate Catering', 'Event Partnerships', 'B2B Sales Process', 'Proposal Writing'],
        learningObjectives: ['Identify 10 corporate target accounts', 'Build B2B proposal template', 'Close first office coffee contract'],
        requiredSkills: ['Sales Fundamentals'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 5,
      },
      {
        id: 'sales-3', name: 'Online & App-Based Sales',
        subtopics: ['Mobile Ordering', 'Delivery Platforms', 'Click & Collect', 'Online Menu Optimization', 'Pre-Order Systems'],
        learningObjectives: ['Launch mobile ordering', 'Optimize delivery platform presence', 'Increase online order %'],
        requiredSkills: [],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 4,
      },
    ],
  },
  {
    id: 'cat-cx',
    name: 'Customer Experience',
    icon: '⭐',
    description: 'Design experiences so remarkable they become the story customers tell — your best marketing.',
    completionPercentage: 0,
    updatedAt: now,
    topics: [
      {
        id: 'cx-1', name: 'Customer Journey Mapping',
        subtopics: ['Journey Stages (Awareness to Advocacy)', 'Touchpoint Inventory', 'Pain Points & Moments of Delight', 'Emotional Journey', 'Journey Redesign'],
        learningObjectives: ['Map complete CoffeePlace customer journey', 'Identify 3 pain points to eliminate', 'Design 3 wow moments'],
        requiredSkills: [],
        difficulty: 'beginner', completed: false, notes: '', estimatedHours: 4,
      },
      {
        id: 'cx-2', name: 'Service Design',
        subtopics: ['Service Blueprint', 'Front-of-House Design', 'Queue Management', 'Peak Hour Experience', 'Service Recovery Protocol'],
        learningObjectives: ['Build CoffeePlace service blueprint', 'Design peak-hour flow', 'Create service recovery playbook'],
        requiredSkills: ['Customer Journey Mapping'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 5,
      },
      {
        id: 'cx-3', name: 'Customer Feedback Systems',
        subtopics: ['NPS Measurement', 'Google Review Strategy', 'Social Listening', 'In-Store Feedback', 'Complaint Resolution'],
        learningObjectives: ['Launch monthly NPS survey', 'Build review response system', 'Create complaint resolution SOP'],
        requiredSkills: [],
        difficulty: 'beginner', completed: false, notes: '', estimatedHours: 3,
      },
      {
        id: 'cx-4', name: 'Loyalty & Advocacy Programs',
        subtopics: ['Points-Based Loyalty', 'Tiered Membership', 'Referral Mechanics', 'Surprise & Delight', 'Ambassador Program'],
        learningObjectives: ['Design loyalty program P&L', 'Launch referral program', 'Calculate loyalty program ROI'],
        requiredSkills: ['Customer Feedback Systems'],
        difficulty: 'advanced', completed: false, notes: '', estimatedHours: 5,
      },
    ],
  },
  {
    id: 'cat-expansion',
    name: 'Expansion',
    icon: '🏗️',
    description: 'The systems, capital, and strategy to go from 1 to 10+ branches as a regional brand.',
    completionPercentage: 0,
    updatedAt: now,
    topics: [
      {
        id: 'exp-1', name: 'Multi-Unit Financial Modeling',
        subtopics: ['Unit-Level P&L', 'Portfolio P&L', '5-Branch Financial Model', 'Ramp Period Assumptions', 'Cash Requirements per New Branch'],
        learningObjectives: ['Build 5-branch financial model', 'Calculate capital required for expansion', 'Model ramp-up period per location'],
        requiredSkills: ['Financial Statements', 'Unit Economics'],
        difficulty: 'advanced', completed: false, notes: '', estimatedHours: 8,
      },
      {
        id: 'exp-2', name: 'Site Selection',
        subtopics: ['Site Criteria Matrix', 'Foot Traffic Analysis', 'Demographic Profiling', 'Competitor Proximity', 'Lease Economics'],
        learningObjectives: ['Build site scoring matrix', 'Analyze foot traffic data', 'Evaluate 3 real potential sites'],
        requiredSkills: ['Commercial Lease Negotiation'],
        difficulty: 'intermediate', completed: false, notes: '', estimatedHours: 5,
      },
      {
        id: 'exp-3', name: 'Franchise vs Company-Owned Model',
        subtopics: ['Franchise Economics', 'FDD Basics', 'Company-Owned Scaling', 'License Model', 'Joint Venture Structure', 'Pros/Cons Analysis'],
        learningObjectives: ['Model franchise vs company-owned economics', 'Understand FDD requirements', 'Choose optimal expansion model for CoffeePlace'],
        requiredSkills: ['Multi-Unit Financial Modeling'],
        difficulty: 'advanced', completed: false, notes: '', estimatedHours: 6,
      },
      {
        id: 'exp-4', name: 'Brand Standards & Scalability',
        subtopics: ['Brand Standards Manual', 'Product Consistency Across Branches', 'Central Kitchen/Production', 'Regional Manager Role', 'Tech Stack for Scale'],
        learningObjectives: ['Build brand standards manual', 'Design central production model', 'Create regional manager scorecard'],
        requiredSkills: ['Multi-Branch Operations'],
        difficulty: 'advanced', completed: false, notes: '', estimatedHours: 6,
      },
    ],
  },
]

// ─── Default Skill Scores ─────────────────────────────────────────────────────

import { ALL_MBA_CATEGORIES } from './types'

export const SEED_SKILL_SCORES: SkillScore[] = ALL_MBA_CATEGORIES
  .filter(c => c !== 'Other')
  .map(category => ({
    id: `skill-${category.toLowerCase().replace(/[\s&]/g, '-')}`,
    category,
    currentScore: 0,
    targetScore: 80,
    previousScore: 0,
    evidence: [],
    lastUpdated: now,
  }))
