import { CaseStudy } from './types'

const now = new Date().toISOString()

export const SEED_CASE_STUDIES: CaseStudy[] = [
  {
    id: 'cs-starbucks',
    company: 'Starbucks',
    industry: 'Specialty Coffee',
    category: 'Strategy',
    founded: '1971',
    headquarters: 'Seattle, USA',
    summary: 'Starbucks transformed coffee from a commodity into an experience-led premium brand. Howard Schultz rebuilt the company around the concept of the "third place" — a space between home and work. They scaled from 11 stores to 35,000+ globally through company-owned expansion, licensing, and eventually a successful franchise model in select markets.',
    keyLessons: [
      'Experience-led branding can command premium pricing across all demographics',
      'Technology adoption (mobile app, loyalty) can drive 25%+ of revenue',
      'Standardization of product + localization of experience = scalable brand',
      'Vertical integration (owning roasting) builds cost advantages at scale',
      '"Third place" positioning creates habitual daily visits',
    ],
    strengths: [
      'World\'s most recognized coffee brand with massive loyalty program (32M+ members)',
      'Best-in-class technology: mobile ordering, personalization, payment',
      'Global supply chain with direct sourcing relationships',
      'Strong real estate / location strategy',
    ],
    weaknesses: [
      'Premium pricing vulnerable in economic downturns',
      'Over-expansion led to diluted brand experience',
      'High complexity menu slows service and creates inconsistency',
      'Corporate feel has weakened authentic coffee community connection',
    ],
    coffeeApplications: [
      'Model CoffeePlace loyalty program on Starbucks app mechanics but boutique feel',
      'Use standardization principles for quality without losing specialty identity',
      'Apply "third place" positioning to location design and dwell-time strategy',
      'Study their barista training model for skills certification program',
    ],
    isSeeded: true,
    createdAt: now, updatedAt: now,
  },
  {
    id: 'cs-blue-bottle',
    company: 'Blue Bottle Coffee',
    industry: 'Specialty Coffee',
    category: 'Branding',
    founded: '2002',
    headquarters: 'Oakland, USA',
    summary: 'Blue Bottle pioneered the "third wave" specialty coffee movement and built a premium brand on radical simplicity — no Wi-Fi, no distractions, just exceptional coffee. They raised $120M from investors including Nestle (now majority owner) by building a cult following through quality-obsessed branding before ever thinking about scale.',
    keyLessons: [
      'Radical simplicity is a brand strategy, not an oversight',
      'Quality obsession in early stages builds brand equity that enables premium pricing forever',
      'Cult brands are built by deeply serving a niche before expanding',
      'Specialty coffee is a story business — origin, process, and craft must be communicated',
      'Institutional investment can help scale but risks diluting brand DNA',
    ],
    strengths: [
      'Exceptionally strong brand identity and design aesthetic',
      'Best-in-class barista training and coffee quality standards',
      'Strong direct subscription business (online retail)',
      'Premium positioning maintained even after scale',
    ],
    weaknesses: [
      'High cost structure limits mass-market expansion',
      'Wi-Fi-free policy limits dwell time and community building',
      'Nestle acquisition has raised questions about independence and ethos',
    ],
    coffeeApplications: [
      'Build CoffeePlace brand on quality obsession — let that drive all decisions',
      'Invest in origin storytelling to justify premium pricing',
      'Develop a direct subscription model for beans (recurring revenue stream)',
      'Study their minimal design aesthetic for CoffeePlace visual identity',
    ],
    isSeeded: true,
    createdAt: now, updatedAt: now,
  },
  {
    id: 'cs-arabica',
    company: '% Arabica',
    industry: 'Specialty Coffee',
    category: 'Branding',
    founded: '2013',
    headquarters: 'Kyoto, Japan',
    summary: '% Arabica became one of the most Instagrammed coffee brands in the world by treating every store as a piece of architecture and art. Founded in Kyoto, they scaled to 100+ locations across 30 countries by building a brand that is visually distinctive, spatially premium, and product-focused. Their expansion into the Middle East has been particularly successful.',
    keyLessons: [
      'Visual identity can be a complete growth engine — Instagram-worthy design drives organic reach',
      'Architecture and space design ARE marketing at premium positioning',
      'Keeping menu simple (coffee only, done perfectly) is a growth strategy',
      'Premium experience brands have disproportionate international appeal',
    ],
    strengths: [
      'World-class visual identity and store design that generates massive organic social media',
      'Tight menu focus creates operational simplicity and quality consistency',
      'Strong international brand that resonates particularly well in Asia and MENA',
      'Premium pricing fully justified by experience quality',
    ],
    weaknesses: [
      'Very high fit-out costs limit speed of expansion',
      'Menu simplicity limits average ticket size',
      'Limited non-coffee options reduces accessibility',
    ],
    coffeeApplications: [
      'Invest in CoffeePlace store design as a primary marketing vehicle',
      'Consider how CoffeePlace can become the most photographed cafe in your city',
      'Study % Arabica\'s MENA expansion strategy as direct parallel to CoffeePlace market',
      'Evaluate the simple menu model — fewer items, higher quality vs large menu',
    ],
    isSeeded: true,
    createdAt: now, updatedAt: now,
  },
  {
    id: 'cs-costa',
    company: 'Costa Coffee',
    industry: 'Coffee Chain',
    category: 'Operations',
    founded: '1971',
    headquarters: 'Dunstable, UK',
    summary: "Costa Coffee grew from a single London roastery to the UK's largest coffee chain (2,400+ UK locations) and was acquired by Coca-Cola for $5.1 billion in 2019. Their success was built on systematic operations, aggressive high-street and transit location strategy, and the development of a vending machine network (Costa Express) that democratized premium coffee access.",
    keyLessons: [
      'Systemized operations and consistency at scale is a defensible competitive advantage',
      'Location strategy (high footfall, transit, drive-thru) matters more than experience in mass market',
      'Vending and self-serve extensions can dramatically expand unit economics',
      'Loyalty programs (Costa Club) are worth building early — they became a key acquisition asset',
    ],
    strengths: [
      'Exceptional operational consistency across thousands of locations',
      'Diverse channel strategy (cafes, express machines, drive-thrus, delivery)',
      'Strong franchise model that accelerates geographic expansion',
      'Costa Express vending creates high-margin, low-labor revenue stream',
    ],
    weaknesses: [
      'Brand perceived as mass-market, struggles to compete with specialty players on quality perception',
      'Coca-Cola ownership raises questions about long-term brand direction',
    ],
    coffeeApplications: [
      'Study Costa\'s operations manual as a template for CoffeePlace SOP development',
      'Model the channel diversification strategy for CoffeePlace Phase 2 (vending, catering)',
      'Use Costa\'s franchise model as a reference when designing CoffeePlace expansion',
      'Build loyalty program early — it was a major driver of Costa\'s acquisition value',
    ],
    isSeeded: true,
    createdAt: now, updatedAt: now,
  },
  {
    id: 'cs-sweetgreen',
    company: 'Sweetgreen',
    industry: 'Fast Casual F&B',
    category: 'Entrepreneurship',
    founded: '2007',
    headquarters: 'Los Angeles, USA',
    summary: 'Sweetgreen (salad chain) became a $1B+ company by connecting mission, food quality, and technology in a category not previously seen as investable. Three Georgetown students built a brand on supply chain transparency, digital-first ordering, and a loyalty community — then IPO\'d in 2021. Their lessons on mission-driven brand building apply directly to specialty coffee.',
    keyLessons: [
      'Mission-driven brands attract both customers AND talent disproportionately',
      'Digital-first ordering from early days creates powerful data and customer relationships',
      'Farm-to-fork supply chain transparency is a competitive moat in food',
      'Community before scale — their loyal customers drove early growth organically',
    ],
    strengths: [
      'Industry-leading digital adoption (70%+ digital orders)',
      'Strong mission and sustainability story resonates with target customers',
      'Automated restaurant technology (Infinite Kitchen) building future operational advantage',
    ],
    weaknesses: [
      'Not yet profitable despite decade+ of operations and IPO',
      'Premium pricing limits TAM significantly',
    ],
    coffeeApplications: [
      'Apply mission-driven branding to CoffeePlace — why you source the way you do matters',
      'Invest in digital ordering early — it is the path to customer data and loyalty',
      'Study their supply chain transparency story for CoffeePlace origin communications',
      'Community-building approach directly applicable to specialty coffee audience',
    ],
    isSeeded: true,
    createdAt: now, updatedAt: now,
  },
  {
    id: 'cs-chipotle',
    company: 'Chipotle Mexican Grill',
    industry: 'Fast Casual F&B',
    category: 'Operations',
    founded: '1993',
    headquarters: 'Newport Beach, USA',
    summary: 'Chipotle built a $50B+ company by doing a few things exceptionally well: a simple menu with high-quality ingredients, ruthlessly efficient operations (assembly line service), and an unwavering brand promise. Their recovery from a 2015 food safety crisis and subsequent $1,000+ stock price recovery is one of the greatest comeback stories in F&B.',
    keyLessons: [
      '"Food with Integrity" positioning justifies premium pricing and attracts quality-conscious customers',
      'Assembly-line service model maximizes throughput without sacrificing customization',
      'Crisis management: transparency and over-communication rebuilt trust post-food safety incident',
      'Digital channel investment (app, delivery) added massive revenue without additional locations',
      'Simple menu + great execution beats complex menu + average execution every time',
    ],
    strengths: [
      'Operational efficiency at scale is best-in-class in fast casual category',
      'Strong digital business generates 35%+ of revenue',
      'Loyal customer base with strong app engagement',
      'Real estate strategy (suburban + urban) highly diversified',
    ],
    weaknesses: [
      'Food safety track record remains a brand vulnerability',
      'Limited international presence compared to domestic scale',
    ],
    coffeeApplications: [
      'Apply Chipotle\'s operational simplicity principle to CoffeePlace menu design',
      'Study their food safety recovery as a crisis management playbook',
      'Model CoffeePlace digital strategy on Chipotle\'s app-first approach',
      'Use "Coffee with Integrity" as positioning framework — source transparency as differentiator',
    ],
    isSeeded: true,
    createdAt: now, updatedAt: now,
  },
  {
    id: 'cs-pret',
    company: 'Pret A Manger',
    industry: 'Food & Coffee Retail',
    category: 'Customer Experience',
    founded: '1983',
    headquarters: 'London, UK',
    summary: "Pret A Manger built a legendary brand around genuine hospitality, freshly made food, and a culture so strong that their staff's friendliness became a competitive advantage. Their subscription coffee model (Coffee Club, ~£30/month for unlimited coffee) is one of the most successful F&B subscription launches in history — driving 60%+ subscription revenue growth and transforming their business model.",
    keyLessons: [
      'Culture is the product — Pret\'s customer experience is a direct output of their staff culture',
      'Coffee subscription changed their entire unit economics and created massive recurring revenue',
      'Freshness as a brand pillar (no preservatives, made today) creates trust and justifies premium',
      'Staff happiness directly correlates with customer experience quality',
    ],
    strengths: [
      'Subscription model creates predictable, recurring revenue and drives daily visit habits',
      'Staff culture and training is industry-leading — consistently ranked highest for service',
      'Fresh, made-daily food creates genuine brand differentiation',
    ],
    weaknesses: [
      'Heavy reliance on commuter/office foot traffic made them vulnerable to remote work shift',
      'Subscription pricing can depress average revenue per customer if not managed carefully',
    ],
    coffeeApplications: [
      'Explore a CoffeePlace subscription model (monthly unlimited coffee) — model the economics',
      'Invest in staff culture as a primary competitive advantage, not just an HR exercise',
      'Study Pret\'s hiring approach — they hire for personality and happiness, train for skills',
      'Fresh, made-to-order food can be a differentiator for CoffeePlace to explore',
    ],
    isSeeded: true,
    createdAt: now, updatedAt: now,
  },
]

// ─── Seeded Exams ─────────────────────────────────────────────────────────────
