import { MBAMonth, Course, Settings } from './types'
import { generateId } from './utils'

const now = new Date().toISOString()

export const SEED_MBA_MONTHS: MBAMonth[] = [
  {
    id: 'month-1',
    monthNumber: 1,
    name: 'Business Foundations',
    focus: 'Master the financial and operational fundamentals every founder must know',
    goals: [
      'Understand P&L, balance sheet, and cash flow statements',
      'Build CoffeePlace unit economics model',
      'Learn basic accounting principles',
      'Define your business model canvas',
    ],
    topics: ['Financial Literacy', 'Accounting Basics', 'Unit Economics', 'Business Model Design'],
    subtopics: {
      'Financial Literacy': ['P&L Statement', 'Balance Sheet', 'Cash Flow Statement', 'Working Capital'],
      'Accounting Basics': ['Revenue Recognition', 'COGS vs OpEx', 'Gross Margin', 'EBITDA'],
      'Unit Economics': ['CAC', 'LTV', 'Payback Period', 'Contribution Margin per Cup'],
      'Business Model Design': ['Business Model Canvas', 'Value Proposition', 'Revenue Streams', 'Cost Structure'],
    },
    recommendedCourses: [],
    assignments: [
      { id: generateId(), title: 'Build CoffeePlace P&L Template', description: 'Create a monthly P&L model for one branch', dueDate: '', status: 'pending' },
      { id: generateId(), title: 'Calculate Unit Economics', description: 'Cost per cup, average ticket, gross margin per branch', dueDate: '', status: 'pending' },
      { id: generateId(), title: 'Complete Business Model Canvas', description: 'Fill out all 9 blocks for CoffeePlace', dueDate: '', status: 'pending' },
    ],
    coffeeImplementation: 'Build a real financial model for your first branch. Calculate the exact cost per drink, average ticket size, target gross margin (70%+), and monthly break-even point.',
    checklist: [
      { id: generateId(), label: 'Read: Profit First or Financial Intelligence', completed: false },
      { id: generateId(), label: 'Build P&L template in Excel/Sheets', completed: false },
      { id: generateId(), label: 'Calculate cost per cup for top 5 drinks', completed: false },
      { id: generateId(), label: 'Map CoffeePlace Business Model Canvas', completed: false },
      { id: generateId(), label: 'Complete Month 1 assignments', completed: false },
      { id: generateId(), label: 'Week 4: CEO Review against goals', completed: false },
    ],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'month-2',
    monthNumber: 2,
    name: 'Operations & Systems',
    focus: 'Build repeatable, scalable systems that work without you',
    goals: [
      'Document your core SOPs for bar operations',
      'Design quality control framework',
      'Build inventory management system',
      'Create the CoffeePlace training manual structure',
    ],
    topics: ['SOP Development', 'Supply Chain', 'Quality Control', 'Training Systems'],
    subtopics: {
      'SOP Development': ['Process Mapping', 'Standard Work', 'Visual Management', 'Checklists'],
      'Supply Chain': ['Supplier Selection', 'Green Coffee Sourcing', 'Inventory Turns', 'Par Levels'],
      'Quality Control': ['Barista Protocols', 'Sensory Standards', 'Waste Tracking', 'Customer Complaints'],
      'Training Systems': ['Onboarding Flow', 'Skills Matrix', 'Certification Levels', 'Performance Metrics'],
    },
    recommendedCourses: [],
    assignments: [
      { id: generateId(), title: 'Write 5 Core SOPs', description: 'Opening, closing, espresso dialing, milk steaming, cleaning', dueDate: '', status: 'pending' },
      { id: generateId(), title: 'Design Inventory System', description: 'Par levels, reorder points, waste log', dueDate: '', status: 'pending' },
      { id: generateId(), title: 'Create Training Checklist', description: 'Week 1-4 barista onboarding checklist', dueDate: '', status: 'pending' },
    ],
    coffeeImplementation: 'Build the CoffeePlace Operations Manual v1. Document every repeatable process so a new hire can run the bar without you. Start with the top 10 highest-impact SOPs.',
    checklist: [
      { id: generateId(), label: 'Map current bar workflow end-to-end', completed: false },
      { id: generateId(), label: 'Write Opening & Closing SOP', completed: false },
      { id: generateId(), label: 'Write Espresso Dialing SOP', completed: false },
      { id: generateId(), label: 'Build inventory par levels spreadsheet', completed: false },
      { id: generateId(), label: 'Design 30-day barista onboarding checklist', completed: false },
      { id: generateId(), label: 'Complete Month 2 assignments', completed: false },
    ],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'month-3',
    monthNumber: 3,
    name: 'Marketing & Brand',
    focus: 'Build a brand people love and a marketing engine that grows with you',
    goals: [
      'Define CoffeePlace brand identity (mission, voice, positioning)',
      'Build customer acquisition strategy',
      'Launch content marketing framework',
      'Design loyalty and retention system',
    ],
    topics: ['Brand Strategy', 'Digital Marketing', 'Content Creation', 'Customer Retention'],
    subtopics: {
      'Brand Strategy': ['Brand Positioning', 'Target Customer Profile', 'Brand Voice', 'Visual Identity'],
      'Digital Marketing': ['Instagram Strategy', 'Google My Business', 'Email Marketing', 'Local SEO'],
      'Content Creation': ['Content Calendar', 'Coffee Education Content', 'Behind the Scenes', 'UGC Strategy'],
      'Customer Retention': ['Loyalty Program Design', 'NPS Measurement', 'VIP Customer Strategy', 'Referral Programs'],
    },
    recommendedCourses: [],
    assignments: [
      { id: generateId(), title: 'Write Brand Manifesto', description: "CoffeePlace's mission, values, personality, and promise", dueDate: '', status: 'pending' },
      { id: generateId(), title: 'Build 90-Day Content Calendar', description: 'Instagram posts, stories, reels plan', dueDate: '', status: 'pending' },
      { id: generateId(), title: 'Design Loyalty Program', description: 'Points system, tiers, rewards structure', dueDate: '', status: 'pending' },
    ],
    coffeeImplementation: "Define what makes CoffeePlace's brand unmistakable in your market. Build the content engine that turns customers into advocates. Every specialty coffee brand that scales does so on the back of a strong community.",
    checklist: [
      { id: generateId(), label: 'Write brand positioning statement', completed: false },
      { id: generateId(), label: 'Define ideal customer profile (ICP)', completed: false },
      { id: generateId(), label: 'Audit current social media presence', completed: false },
      { id: generateId(), label: 'Build 30-day content calendar', completed: false },
      { id: generateId(), label: 'Design loyalty program structure', completed: false },
      { id: generateId(), label: 'Complete Month 3 assignments', completed: false },
    ],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'month-4',
    monthNumber: 4,
    name: 'Strategy & Competitive Advantage',
    focus: 'Think like a strategist — build a moat, not just a coffee shop',
    goals: [
      'Apply Porter\'s Five Forces to the local coffee market',
      'Define CoffeePlace\'s sustainable competitive advantage',
      'Identify and map top competitors',
      'Build a 3-year strategic roadmap',
    ],
    topics: ["Porter's Five Forces", 'Blue Ocean Strategy', 'Competitive Analysis', 'Strategic Planning'],
    subtopics: {
      "Porter's Five Forces": ['Supplier Power', 'Buyer Power', 'Competitive Rivalry', 'Threat of Substitutes', 'New Entrants'],
      'Blue Ocean Strategy': ['Value Innovation', 'ERRC Framework', 'Strategy Canvas', 'Non-customers'],
      'Competitive Analysis': ['Competitor Mapping', 'SWOT Analysis', 'Pricing Analysis', 'Gap Analysis'],
      'Strategic Planning': ['Vision & Mission', 'OKRs', '3-Year Roadmap', 'Strategic Priorities'],
    },
    recommendedCourses: [],
    assignments: [
      { id: generateId(), title: 'Five Forces Analysis', description: "Apply Porter's Five Forces to CoffeePlace's local market", dueDate: '', status: 'pending' },
      { id: generateId(), title: 'Competitor Deep Dive', description: 'Profile top 5 competitors across 20 dimensions', dueDate: '', status: 'pending' },
      { id: generateId(), title: 'Write 3-Year Strategic Plan', description: 'Vision, milestones, key bets for CoffeePlace', dueDate: '', status: 'pending' },
    ],
    coffeeImplementation: "Most coffee shops compete on the same dimensions. CoffeePlace must identify its Blue Ocean — the uncontested market space. Map your strategy canvas vs competitors and find the 2-3 dimensions you will own.",
    checklist: [
      { id: generateId(), label: "Complete Porter's Five Forces analysis", completed: false },
      { id: generateId(), label: 'Profile 5 key competitors', completed: false },
      { id: generateId(), label: 'Run SWOT analysis for CoffeePlace', completed: false },
      { id: generateId(), label: 'Define 3-year strategic vision', completed: false },
      { id: generateId(), label: 'Set annual OKRs', completed: false },
      { id: generateId(), label: 'Complete Month 4 assignments', completed: false },
    ],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'month-5',
    monthNumber: 5,
    name: 'Leadership & Team Building',
    focus: 'Build a team that delivers the CoffeePlace experience without you',
    goals: [
      'Design the ideal CoffeePlace org structure',
      'Build a hiring and onboarding system',
      'Learn performance management fundamentals',
      'Develop your leadership philosophy',
    ],
    topics: ['Hiring & Recruiting', 'Performance Management', 'Culture Building', 'Leadership Development'],
    subtopics: {
      'Hiring & Recruiting': ['Job Profile Design', 'Interview Scorecards', 'Barista Testing', 'Culture Fit Assessment'],
      'Performance Management': ['KPIs per Role', '1-on-1 Structure', 'Review Cadence', 'PIPs'],
      'Culture Building': ['Values in Action', 'Team Rituals', 'Recognition Programs', 'Psychological Safety'],
      'Leadership Development': ['Delegation Framework', 'Decision Rights', 'Coaching vs Managing', 'Founder Traps'],
    },
    recommendedCourses: [],
    assignments: [
      { id: generateId(), title: 'Design Org Chart', description: 'Current state and 12-month future state org chart', dueDate: '', status: 'pending' },
      { id: generateId(), title: 'Write Head Barista Job Profile', description: 'Role, responsibilities, KPIs, competencies', dueDate: '', status: 'pending' },
      { id: generateId(), title: 'Build Performance Review Template', description: 'Monthly 1-on-1 agenda and quarterly review framework', dueDate: '', status: 'pending' },
    ],
    coffeeImplementation: "The biggest constraint to scaling CoffeePlace won't be capital — it'll be people. Build systems that attract, develop, and retain great baristas and managers. Your culture IS your product quality.",
    checklist: [
      { id: generateId(), label: 'Map current team structure', completed: false },
      { id: generateId(), label: 'Write job profiles for all roles', completed: false },
      { id: generateId(), label: 'Build interview scorecard', completed: false },
      { id: generateId(), label: 'Design 30-60-90 day onboarding plan', completed: false },
      { id: generateId(), label: 'Write your leadership principles', completed: false },
      { id: generateId(), label: 'Complete Month 5 assignments', completed: false },
    ],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'month-6',
    monthNumber: 6,
    name: 'Scale & Expansion',
    focus: 'Build the infrastructure to go from 1 to 5+ branches',
    goals: [
      'Model the financial requirements for expansion',
      'Design the multi-branch operating model',
      'Explore funding options and investor readiness',
      'Build the CoffeePlace expansion playbook',
    ],
    topics: ['Multi-Unit Operations', 'Fundraising & Capital', 'Franchising vs Company-Owned', 'Exit Strategy'],
    subtopics: {
      'Multi-Unit Operations': ['Central Kitchen Model', 'Area Manager Role', 'Brand Standards', 'Tech Stack for Scale'],
      'Fundraising & Capital': ['Bootstrapping', 'Angel Investors', 'Bank Loans', 'Pitch Deck Basics'],
      'Franchising vs Company-Owned': ['Unit Economics at Scale', 'Franchise Model Pros/Cons', 'License Model', 'JV Structures'],
      'Exit Strategy': ['Strategic Buyer', 'PE Rollup', 'IPO Basics', 'ESOP'],
    },
    recommendedCourses: [],
    assignments: [
      { id: generateId(), title: 'Build 5-Branch Financial Model', description: 'Revenue, costs, and cash requirements for 5 branches', dueDate: '', status: 'pending' },
      { id: generateId(), title: 'Write Expansion Playbook', description: 'Site selection, launch checklist, ramp model for new branches', dueDate: '', status: 'pending' },
      { id: generateId(), title: 'Create Investor-Ready Summary', description: 'One-page executive summary of CoffeePlace for investors', dueDate: '', status: 'pending' },
    ],
    coffeeImplementation: "Design the CoffeePlace Expansion Playbook — the document that lets you open a new branch every 6 months with confidence. Model what it takes to reach 5 branches and what funding you need to get there.",
    checklist: [
      { id: generateId(), label: 'Build 3-year multi-branch P&L model', completed: false },
      { id: generateId(), label: 'Define site selection criteria', completed: false },
      { id: generateId(), label: 'Research funding options in your market', completed: false },
      { id: generateId(), label: 'Write expansion playbook draft', completed: false },
      { id: generateId(), label: 'Create one-page investor summary', completed: false },
      { id: generateId(), label: 'MBA Graduation: 6-month retrospective', completed: false },
    ],
    createdAt: now, updatedAt: now,
  },
]

export const DEFAULT_SETTINGS: Settings = {
  founderName: 'Kero',
  brandName: 'CoffeePlace',
  startDate: new Date().toISOString().split('T')[0],
  currentMonth: 1,
  theme: 'light',
}
