import { Book } from './types'

const now = new Date().toISOString()

export const SEED_BOOKS: Book[] = [
  {
    id: 'book-1',
    name: 'The E-Myth Revisited',
    author: 'Michael Gerber',
    category: 'Entrepreneurship',
    progress: 0, status: 'want_to_read',
    summary: '',
    notes: '',
    actionItems: ['Identify which Technician tasks you can systemize', 'Build your first SOP this week'],
    coffeeApplications: ['Replace yourself in every bar task with a documented system', 'Build CoffeePlace to work without you there'],
    rating: 0,
    createdAt: now, updatedAt: now,
  },
  {
    id: 'book-2',
    name: 'Profit First',
    author: 'Mike Michalowicz',
    category: 'Finance',
    progress: 0, status: 'want_to_read',
    summary: '',
    notes: '',
    actionItems: ['Open separate bank accounts for Profit, Tax, Operating Expenses', 'Set first Profit First allocation percentages'],
    coffeeApplications: ['Implement Profit First system for CoffeePlace cash management', 'Set profit aside FIRST before paying expenses'],
    rating: 0,
    createdAt: now, updatedAt: now,
  },
  {
    id: 'book-3',
    name: 'Good to Great',
    author: 'Jim Collins',
    category: 'Strategy',
    progress: 0, status: 'want_to_read',
    summary: '',
    notes: '',
    actionItems: ['Identify CoffeePlace Hedgehog Concept', 'Build Level 5 Leadership behaviors'],
    coffeeApplications: ['Apply the Hedgehog Concept: what can CoffeePlace be the best at?', 'Build a flywheel model for CoffeePlace growth'],
    rating: 0,
    createdAt: now, updatedAt: now,
  },
  {
    id: 'book-4',
    name: 'Raving Fans',
    author: 'Ken Blanchard',
    category: 'Customer Experience',
    progress: 0, status: 'want_to_read',
    summary: '',
    notes: '',
    actionItems: ['Define what CoffeePlace PLUS-1 looks like for customers', 'Train team on exceeding expectations by 1%'],
    coffeeApplications: ['Design 3 raving fan moments in the CoffeePlace experience', 'Create service recovery protocol that turns complaints into fans'],
    rating: 0,
    createdAt: now, updatedAt: now,
  },
  {
    id: 'book-5',
    name: 'Blue Ocean Strategy',
    author: 'W. Chan Kim & Renée Mauborgne',
    category: 'Strategy',
    progress: 0, status: 'want_to_read',
    summary: '',
    notes: '',
    actionItems: ['Complete ERRC framework for CoffeePlace', 'Build Strategy Canvas vs top 3 competitors'],
    coffeeApplications: ['Find the uncontested market space in your local coffee market', 'Identify what to eliminate from your offering to reduce cost and complexity'],
    rating: 0,
    createdAt: now, updatedAt: now,
  },
  {
    id: 'book-6',
    name: 'The Hard Thing About Hard Things',
    author: 'Ben Horowitz',
    category: 'Leadership',
    progress: 0, status: 'want_to_read',
    summary: '',
    notes: '',
    actionItems: ['Make one hard decision you have been avoiding this week', 'Write a "wartime" and "peacetime" leadership protocol for CoffeePlace'],
    coffeeApplications: ['Apply wartime CEO thinking during tough months', 'Build courage for difficult conversations with team'],
    rating: 0,
    createdAt: now, updatedAt: now,
  },
  {
    id: 'book-7',
    name: 'Measure What Matters (OKRs)',
    author: 'John Doerr',
    category: 'Strategy',
    progress: 0, status: 'want_to_read',
    summary: '',
    notes: '',
    actionItems: ['Write Q1 OKRs for CoffeePlace (3 objectives, 3 KRs each)', 'Set up monthly OKR review cadence'],
    coffeeApplications: ['Implement OKR system for CoffeePlace team alignment', 'Translate 3-year vision into quarterly objectives'],
    rating: 0,
    createdAt: now, updatedAt: now,
  },
]
